### ISSUE TITLE
Does it works with a docker container?

### ISSUE THREAD

**Issue by gersanco** [nrwl/nx-set-shas#118]
Hello,

I have a Github action that installs Playwright but to reduce the execution time I want to use a docker container. So, I added these lines

```
runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
```

Then, when I execute the command 
```
- name: Run Linters
       run: npx nx affected --targets=lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --parallel=3
```

I received an error with this

![image](https://github.com/nrwl/nx-set-shas/assets/12337026/474a21c5-3d1c-4ba8-927e-e7fbeba5515f)

Is there something that I missed?

```
- uses: actions/checkout@v3
        with:
          fetch-depth: 0
- name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master
- name: Run Linters
        run: npx nx affected --targets=lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --parallel=3
```

**Comment by erenken** [comment]
We are having the same problem.  I am trying to run it on a cypress container:

```yaml
  build-test:
    runs-on: self-hosted
      container: cypress/included:latest
```

And when it runs the `nrwl.nx-set-shas@v3` step we get back an empty BASE and empty HEAD

```yaml
      - name: Setup NX
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'
          last-successful-event: 'pull-request'
          workflow-id: 'pr-build-test.yml'
```
This is what is returned by that step:

```
Run nrwl/nx-set-shas@v3
  with:
    main-branch-name: main
    last-successful-event: pull-request
    workflow-id: pr-build-test.yml
    set-environment-variables-for-job: true
    error-on-no-successful-workflow: false
    working-directory: .
Run node "$GITHUB_ACTION_PATH/dist/index.js" "$gh_token" "$main_branch_name" "$error_on_no_successful_workflow" "$last_successful_event" "$working_directory" "$working_id"
  node "$GITHUB_ACTION_PATH/dist/index.js" "$gh_token" "$main_branch_name" "$error_on_no_successful_workflow" "$last_successful_event" "$working_directory" "$working_id"
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    gh_token: ***
    main_branch_name: main
    error_on_no_successful_workflow: false
    last_successful_event: pull-request
    working_directory: .
    working_id: pr-build-test.yml

WARNING: Unable to find a successful workflow run on 'origin/main'
We are therefore defaulting to use HEAD~1 on 'origin/main'

NOTE: You can instead make this a hard error by setting 'error-on-no-successful-workflow' on the action in your workflow.
Run echo "Base SHA"
Base SHA


Head SHA


Run echo "NX_BASE=" >> $GITHUB_ENV
  echo "NX_BASE=" >> $GITHUB_ENV
  echo "NX_HEAD=" >> $GITHUB_ENV
  echo "NX_BASE and NX_HEAD environment variables have been set for the current Job"
  shell: bash --noprofile --norc -e -o pipefail {0}
NX_BASE and NX_HEAD environment variables have been set for the current Job
```

If I don't run this in a container it works fine.

**Comment by gersanco** [comment]
Hello @erenken I could make it works following this https://github.com/actions/runner/issues/1474

I've just added this

```
steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Directory as Safe
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
        shell: bash
```
