### ISSUE TITLE
Versions >= 3.0.2 fail with "Resource not accessible by integration" on merge_group event

### ISSUE THREAD

**Issue by croesnick** [nrwl/nx-set-shas#127]
# Situation

The following workflow fails when triggered as part of a merge queue check:

```yaml
name: Sample

on:
  merge_group:
    types:
      - checks_requested

permissions:
  actions: read
  contents: read

jobs:
  sample:
    runs-on: ubuntu-latest

    steps:
      - uses: nrwl/nx-set-shas
```

# Observation

As reported in https://github.com/nrwl/nx-set-shas/issues/114#issuecomment-1718995109, it works with version 3.0.2. Tested it with 3.3.2 and 4.0.1.

# Expectation

Works with all recent versions on `merge_group` events as well. :)
