### ISSUE TITLE
last-successful-event 'pull_request' question

### ISSUE THREAD

**Issue by Dilvan44** [nrwl/nx-set-shas#134]
First of all I am really thankful for this action as it tremendously helped building the CI/CD pipeline for our monorepo.

I have a question regarding the last-successful-event input parameter:
If I got a job setup like this

```
name: Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This is required to allow the deploy job to read the secrets and shas
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'staging'
          last-successful-event: 'pull_request'`
          
```
and then I merge a PR into staging, would that mean that NX_BASE and NX_HEAD are the same sha?

Because it would than find the just created merge push?
