### ISSUE TITLE
Option to consider different workflow states as successful

### ISSUE THREAD

**Issue by joh-klein** [nrwl/nx-set-shas#146]
We have the following situation: our workflow waits at the very end for approval of the production environment deployment. This only happens occasionally. Thus only then are these workflows considered successful and used as base.

```
- name: Derive appropriate SHAs for base and head for `nx affected` commands
  uses: nrwl/nx-set-shas@v4
  with:
    # The state to check for
    #
    # Default: success
    last-successful-state: "success,waiting"
```
