### ISSUE TITLE
NX_HEAD SHA is wrong

### ISSUE THREAD

**Issue by ryanbas21** [nrwl/nx-set-shas#165]
In my nx app my checkout fails like so:

```
Command failed: git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin 56240dda0825ce8549d4a34ff309575706edc618
17   fatal: remote error: upload-pack: not our ref 56240dda0825ce8549d4a34ff309575706edc618
18   
```

If I look at my local git log, here are the commits (1 commit on feature branch)
<img width="846" alt="Screenshot 2024-08-05 at 9 21 29 AM" src="https://github.com/user-attachments/assets/a6b3a0a2-ac87-435d-8062-0f8697ce27df">

The `HEAD` commit should be `e44c742f167f0f0545ce1e40bf15fca19f842881` but its reading `56240dda0825ce8549d4a34ff309575706edc618`

Here is the set sha's output in my Github action run

<img width="1038" alt="Screenshot 2024-08-05 at 9 23 03 AM" src="https://github.com/user-attachments/assets/0e66f2a3-f35d-42cf-8201-99e64c18341b">

I don't really know why it's started picking up the wrong commit. This seems to happen whenever i've tried doing a pnpm upgrade but i haven't isolated it to specifically changing from `npm` to `pnpm`. I can update here if it continues on a different branch also. I can't see the connection between my work and this, but who knows.

locally if i run `git rev-parse HEAD`

I get: 
e44c742f167f0f0545ce1e40bf15fca19f842881

**Comment by kaankoken** [comment]
is it possible for you to miss to add `fetch-depth: 0` to `actions/checkout@v4`. the example workflow.

```yaml
jobs:
  tests:
    runs-on: ubuntu-latest
    needs: [markdownlint, link-checker]
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - run: pnpm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: master

      - run: pnpm exec nx affected -t test --verbose

```
