### ISSUE TITLE
Base SHA and Head SHA empty

### ISSUE THREAD

**Issue by fourass** [nrwl/nx-set-shas#168]
Hello,
I'm having a weird situation when using the action
When I run it on ubuntu-latest runner it works perfectly
When I run it on a self hosted runner or any docker image, it runs, but never returns the Base SHA and Head SHA

```
get-affected-projects:
    runs-on: ["ubuntu-latest"]
    container:
      image: ${{ vars.CONTAINER_PUBLIC_REGISTRY }}/node:16.14.2-alpine
      credentials:
        username: ${{secrets.CONTAINER_PUBLIC_REGISTRY_USERNAME}}
        password: ${{secrets.CONTAINER_PUBLIC_REGISTRY_TOKEN}}
 steps:
      - name: checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install dependencies
        run: |
          apk --update add bash make git jq
      - name: Set Directory as Safe
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: Get SHAs
        uses: nrwl/nx-set-shas@v4.1.0
```

And this is the return I get 
<img width="1184" alt="image" src="https://github.com/user-attachments/assets/026e4476-2b4b-450d-8c0b-8b4f1c9584d5">
has any one faced this before ? do you have any clues, advices ? I've been struggling for a week now
Thank you
