### ISSUE TITLE
I met `ReferenceError: ReadableStream is not defined` when I use `nrwl/nx-set-shas@v4.1.2` on workflow

### ISSUE THREAD

**Issue by exilee20c** [nrwl/nx-set-shas#173]
![Image](https://github.com/user-attachments/assets/ead3261f-ca39-4a17-9e27-b10bf20bf4a7)

**Comment by korniychuk** [comment]
It looks like an innocent (seemingly) dependency update broke everything 😀

**Comment by v-giorgetti** [comment]
any update on this? should we temporarily switch to an older version?

**Comment by mac2000** [comment]
there is a chance that issue is caused by nodejs versions, probably in your actions you are doing something like:

```yml
- uses: actions/setup-node@v3
  with:
    node-version-file: package.json
- uses: nrwl/nx-set-shas@v4
```

put before, and after something like this:


```yml
- run: node -version
- uses: actions/setup-node@v3
  with:
    node-version-file: package.json
- run: node -version
- uses: nrwl/nx-set-shas@v4
```

just to see what it was before, what you have installed and if that's compatible

technically under the hood, in github actions, pretty fresh version is preinstalled, BUT, if you are using self hosted agents - you are on your own

at the very bad scneartion - there is a chance you gonna need to install it twice - aka one time for this action and second time for app itself

in our case, we are stuck on node v16, which indeed does not know anything about streams 🤷‍♂️

theoretically this action itself may install wanted nodejs version without adding it to the path, which should be quite an easy fix, but is questionable if that worse it

**Comment by meeroslav** [comment]
@exilee20c, what node version are you using?

**Comment by mac2000** [comment]
@meeroslav you probably should be able to reproduce this with setup like this:

```yml
- uses: actions/setup-node@v3
  with:
    node-version: 16
- uses: nrwl/nx-set-shas@v4
```

e.g. `setup-node` will install v16 and add it to the path, so it will become default one, `nx-set-shas` seems to be using default one which may lead to such error (even so it says `node20` which is strange)

may be, workaround will be to switch to composite action and installing desired node or may be there is a way to fix the code, but unfortunately it is not available
