### ISSUE TITLE
Workflow ID detection is broken in v4.1.2

### ISSUE THREAD

**Issue by korniychuk** [nrwl/nx-set-shas#174]
Hi dear NX team 👐 

In the newest release (v4.1.2), the `nx-set-shas` action started to fail due to an error fetching `workflow_id` via the GH API.

- I restarted WF ~10 times, and it failed with the same error.
- Rollback to `v4.1.1` temporarily fixed the issue.
- I assume something is changed in the `oktokit` new version.

#### Step configuration to reproduce
```yml
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref }}
          last-successful-event: schedule # for 'master' workflow (only 1 can be specified. workflow_dispatch - skipped)

```

#### Error screenshots
![Image](https://github.com/user-attachments/assets/80a99b77-16f0-4654-856c-adfa1454cd8a)
![Image](https://github.com/user-attachments/assets/24753942-5dfe-48e2-95b0-9aab444d1ae0)

---

Thanks! 🙏

**Comment by korniychuk** [comment]
UPDATE: We still have NodeJS version `v18.10.0` _(we're going to upgrade soon)_; maybe it'll work on v20.

(I've just read your disclaimer)
> NOTE: The v4 does no longer support deprecated Node versions. The supported version is Node v18+.

**Comment by rafaellucio** [comment]
I have de same problem, and I pass workflow-id in environment and not works too

```
Download action repository 'nrwl/nx-set-shas@v4' (SHA:e2e6dc8bce4b0387a05eb687735c39c41580b792)
Download action repository 'gang-of-front/action-nx-affected-list@main' (SHA:a5f7a1b25c7977f8a7[4](https://github.com/Creditas/benefits-lead-form/actions/runs/11802818118/job/32879336627#step:4:4)7a683265861d0cdb295e7)
Run ./.github/actions/affected
  with:
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***
Run nrwl/nx-set-shas@v4
Run node "$GITHUB_ACTION_PATH/dist/index.js" "$gh_token" "$main_branch_name" "$error_on_no_successful_workflow" "$last_successful_event" "$working_directory" "$working_id" "$fallback_sha"
  node "$GITHUB_ACTION_PATH/dist/index.js" "$gh_token" "$main_branch_name" "$error_on_no_successful_workflow" "$last_successful_event" "$working_directory" "$working_id" "$fallback_sha"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***
    gh_token: ***
    main_branch_name: master
    error_on_no_successful_workflow: false
    last_successful_event: pull_request
    working_directory: .
    working_id: 
    fallback_sha: 

Workflow Id not provided. Using workflow 'undefined'
Error: Process completed with exit code 1.
```

```
runs:
  using: "composite"
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      id: setSHAs
      uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: "master"
        last-successful-event: "pull_request"
        workflow-id: ${{ github.run_id }}
```

![Image](https://github.com/user-attachments/assets/a0b72b96-9a9d-4503-a21e-b2a6c8b04d4e)
