### ISSUE TITLE
4.2.0 fails with "token variable is specified more than once"

### ISSUE THREAD

**Issue by davidchen-allio** [nrwl/nx-set-shas#178]
Hi dear NX team

In the newest release (v4.2.0), the nx-set-shas action started to fail due to an error of an internal package.
```
Error: [@octokit/auth-action] The token variable is specified more than once. Use either `with.token`, `with.GITHUB_TOKEN`, or `env.GITHUB_TOKEN`. See https://github.com/octokit/auth-action.js#createactionauth
```

## Reproducible Steps
```
   - name: Create Github App Token
      id: create-github-app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: some-github-app-id
        private-key: some-github-app-private-key
        owner: ${{ github.repository_owner }}
        repositories: some-repository

   - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ steps.create-github-app-token.outputs.token }}
   
    - uses: nrwl/nx-set-shas@v4
```

## Error Screenshots

<img width="1001" alt="Image" src="https://github.com/user-attachments/assets/432a5860-6381-4e17-a596-5f9af99980c8" />
