### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by renatoaraujoc** [nrwl/nx-set-shas#20]
When issuing a workflow execution for a Pull Request manually with a string, this happens:
![Captura de Tela 2022-02-09 às 23 56 54](https://user-images.githubusercontent.com/358128/153328785-57a0b939-b379-4cdb-b17b-7e4498637492.png)

This is my workflow:
![Captura de Tela 2022-02-10 às 00 00 08](https://user-images.githubusercontent.com/358128/153328958-58eba05a-bcb6-47f8-86f5-ebbc5d1abd5a.png)

I'll try to go back to @v1 which use tags, but... any idea how to fix this with v2?

**Comment by meeroslav** [comment]
Please look at this issue: https://github.com/actions/first-interaction/issues/10

The issue here is that we explicitly expect the event to be `pull_request` otherwise we fall back to finding the last successful commit (which that fails since the `issue_comment` doesn't provide the necessary "resources" to do so).

I will check how can we improve this.

**Comment by meeroslav** [comment]
Investigating this more it doesn't seem to make sense to me.
Why would you want to run the `nx` commands on the comment update/creation?
You would be risking potential misuse and extra runs.

Solution wise, since this is running from the PR, you can simply use bash commands instead on the `nx-set-shas`:
```yaml
- name: Derive NX_BASE and NX_HEAD manually
  shell: bash
  run: |
    echo "NX_BASE=$(echo $(git merge-base origin/main HEAD))"  >> $GITHUB_ENV
    echo "NX_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
```

Adding support for `issue_comment` would overcomplicate the solution and doesn't seem to be valid usage anyway.
