### ISSUE TITLE
set HEAD and BASE based on pull request on closed

### ISSUE THREAD

**Issue by thollander** [nrwl/nx-set-shas#36]
We're deploying ephemeral environments when a pull request is opened on all `affected` projects. 

```yml
on:
  pull_request:
    branches:
      - main
  
jobs:
  main:
    steps:
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      # - ...
      - run: npx nx affected:deploy
```

We'd also like to clean these environments while closing the PR : 

```yml
on:
  pull_request:
    types: [closed]

jobs:
  platform-destroy:
    steps:

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - run: npx nx affected:clean

```

Do you think it could make sens that `nx-set-shas` manages the `HEAD` and `BASE` on pr-closed event the same way it does for a pull request ?
