### ISSUE TITLE
Option to use latest tag of project

### ISSUE THREAD

**Issue by TriPSs** [nrwl/nx-set-shas#41]
Could an option be added that will use the sha of the latest tag of the project instead of the latest successful workflow, as our workflow version bumps all packages and then tags them causing now all projects to be always affected when releasing to prod.

Option like:
```
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
      with:
        main-branch-name: master
        use-tag-latest-tag: true
```
