### ISSUE TITLE
Not a valid object name origin/main

### ISSUE THREAD

**Issue by ggdaltoso** [nrwl/nx-set-shas#43]
Hello everyone 👋 

I'm trying to [setup the CI environment to use Nx Cloud](https://github.com/React95/React95/pull/341) but [I'm getting stuck on changing the target branch from `main` to `master`](https://github.com/React95/React95/pull/341/files#diff-b1be8a945106a48b6637198cfedaca1a78ee3d21e67a050a43bd5cbb022238a8R20-R23). 

The README says we already have such way but it doesn't seem to be working:
```yml
- uses: nrwl/nx-set-shas@v2
  with:
    # The "main" branch of your repository (the base branch which you target with PRs).
    # Common names for this branch include main and master.
    #
    # Default: main
    main-branch-name: ''
```

As you can see in the PR I sent in the beginning, and also in the [Github Action run](https://github.com/React95/React95/runs/6689122813?check_suite_focus=true), the options doesn't seem to be set
![image](https://user-images.githubusercontent.com/6536985/171408019-459bb423-195a-4376-b58a-9e8b9d382e7a.png)

I was digging into the code trying to find where you guys are getting this value and found you're [getting it from `process.env`](https://github.com/nrwl/nx-set-shas/blob/main/find-successful-workflow.js#L10)

```js
const mainBranchName = process.argv[3];
```

Wouldn't be right to get it from the input instead?

```js
const core = require('@actions/core');

// `main-branch-name` input defined in action metadata file
const mainBranchName = core.getInput('main-branch-name') || 'main';
```

Related (probably)
 - https://github.com/nrwl/nx/issues/2170
