### ISSUE TITLE
Question regarding passing environment variables

### ISSUE THREAD

**Issue by mthines** [nrwl/nx-set-shas#49]
Hey.

I'm struggling to get my `test` and `e2e` executors to work in the Github Actions CI, due to missing env variables.

My `spec` and `E2E` depends on data from our `CMS` system, and that is (not surprising) set up using environment variables, to know which `CMS` instance to fetch from.

I've been to follow guide at https://nx.dev/ci/monorepo-ci-github-actions#distributed-ci-with-nx-cloud, but I've been unable to pass Github secrets as variables.

Usually I've been passing the `ENV` at the step level, but I've been unable here with the `yaml` file keeps giving me errors with incorrect type.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/16097850/179344448-805465a7-fbb5-4af0-9acb-0a5ac9153ef3.png">

Can you guys assist me on how to pass variables? 

Thank you!

What I've tried
```diff
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
+     env:
+       STORYBOOK_SANITY_PROJECT_ID: ${{ secrets.STORYBOOK_SANITY_PROJECT_ID }}
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=e2e --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 3
```

Your suggestion:
```yml
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 3
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=test --parallel=3 --ci --code-coverage
        npx nx affected --target=e2e --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 3
```
