### ISSUE TITLE
GITHUB_BASE_REF as default branch name

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx-set-shas#5]
I found it was reasonable for our repositories to use `GITHUB_BASE_REF` as `main-branch-name`.

```yml
uses: nrwl/nx-set-shas@v2
with:
  main-branch-name: {{ github.base_ref}}
```

What if make it default value in the future?
