### ISSUE TITLE
BASE_SHA default set incorrectly

### ISSUE THREAD

**Issue by GeReV** [nrwl/nx-set-shas#51]
The code path which attempts to set a default value on `BASE_SHA` (https://github.com/nrwl/nx-set-shas/blob/e698d52609f0f36b4f79fa52afdae222e3255da7/find-successful-workflow.js#L44-L50) seems to be using an incorrect Git query.

The printout states that "_We are therefore defaulting to use HEAD\~1 on 'origin/${mainBranchName}_".  
However, following statement on line 50: ``BASE_SHA = execSync(`git rev-parse HEAD~1`, { encoding: 'utf-8' });`` queries for `HEAD~1` _on the current branch_, instead of specifying the main branch.

(My assumption here that the printed statement is the expected outcome when the action trigger is `push` and no previous successful run exists).

In addition, if the intention was indeed using the main branch, it seems that using `git rev-parse origin/${mainBranchName}` or the previously set `git merge-base origin/${mainBranchName} HEAD` would be preferred.

My workflow configuration for this action is:
```yml
name: NX Lint
on:
  push:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=lint --parallel=3
```

**Comment by meeroslav** [comment]
Hey @GeReV,

thank you for reporting this. Indeed, the wording here is not 100% clear.

The assumption (and intended usage of this action) is to run the action or pull request to the main branch or push on the main. 

Therefore if you're already in the `else` branch on https://github.com/nrwl/nx-set-shas/blob/e698d52609f0f36b4f79fa52afdae222e3255da7/find-successful-workflow.js#L29-L31 the assumption is that the event is running on the main branch. Of course, this might not be the case if you configured your workflow to be other than (e.g. using tags, listening to events on release, develop etc. branches):

```yml
on:
  push:
    branches:
      - main
  pull_request:
```

In practice, it should not make a difference, but using `git rev-parse origin/${mainBranchName}~1` would be more accurate.
