### ISSUE TITLE
Failing builds

### ISSUE THREAD

**Issue by charsleysa** [nrwl/nx-set-shas#57]
It seems the latest commit has incremented the version number and included a commit for PR #52 which is breaking builds for master branches.

I'm getting the following error:
```
Run nrwl/nx-set-shas@v2
  with:
    set-environment-variables-for-job: true
    error-on-no-successful-workflow: false
    last-successful-event: push
    working-directory: .
  env:
    FLY_VERSION: latest
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    BUILD_CONFIG: staging
    DEPLOY_ENVIRONMENT: staging
Run node $GITHUB_ACTION_PATH/dist/index.js ***  false push . 
  node $GITHUB_ACTION_PATH/dist/index.js ***  false push . 
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    FLY_VERSION: latest
    NX_CLOUD_DISTRIBUTED_EXECUTION: true
    BUILD_CONFIG: staging
    DEPLOY_ENVIRONMENT: staging

WARNING: Working directory 'undefined' doesn't exist.
(node:1650) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Workflow Id not provided. Using workflow '3725635'

WARNING: Unable to find a successful workflow run on 'origin/false'
We are therefore defaulting to use HEAD~1 on 'origin/false'

NOTE: You can instead make this a hard error by setting 'error-on-no-successful-workflow' on the action in your workflow.
fatal: ambiguous argument 'origin/false~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
node:internal/errors:856
  const err = new Error(message);
              ^

Error: Command failed: git rev-parse origin/false~1
fatal: ambiguous argument 'origin/false~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (node:child_process:841:11)
    at execSync (node:child_process:912:15)
    at /home/runner/work/_actions/nrwl/nx-set-shas/v2/dist/index.js:62843:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 128,
  signal: null,
  output: [
    null,
    'origin/false~1\n',
    "fatal: ambiguous argument 'origin/false~1': unknown revision or path not in the working tree.\n" +
      "Use '--' to separate paths from revisions, like this:\n" +
      "'git <command> [<revision>...] -- [<file>...]'\n"
  ],
  pid: 1665,
  stdout: 'origin/false~1\n',
  stderr: "fatal: ambiguous argument 'origin/false~1': unknown revision or path not in the working tree.\n" +
    "Use '--' to separate paths from revisions, like this:\n" +
    "'git <command> [<revision>...] -- [<file>...]'\n"
}
Error: Process completed with exit code 1.
```

cc @LayZeeDK

**Comment by LayZeeDK** [comment]
You are correct, @charsleysa. It seems that #52 forgot to include a version bump in `package.json`, so the [publish](https://github.com/nrwl/nx-set-shas/blob/eae3c656f8ec9ab22bb442f0f30768663ab611ea/.github/workflows/publish.yml) workflow was never triggered. With #55 including a version bump, #52 was only just part of a tagged release.

A few questions to help this project find the best path forward to resolving this issue:
1. Are you using `fetch-depth: 0` as required by this action so that `origin/*` branches are available to the runner?
  ```yaml
  - uses: actions/checkout@v3
    with:
      # We need to fetch all branches and commits so that Nx affected has a base to compare against.
      fetch-depth: 0
  ```
2. Does `v2.2.3` work for you?
  ```yaml
  - name: Derive appropriate SHAs for base and head for `nx affected` commands
    uses: nrwl/nx-set-shas@v2.2.3
  ```
3. Does the commit version of #52 work for you?
  ```yaml
  - name: Derive appropriate SHAs for base and head for `nx affected` commands
    uses: nrwl/nx-set-shas@87839d6fba2ae7c5c7fd235475c0a59c58099fb8
  ```

**Comment by ShayDavidson** [comment]
We have the same issue, builds started failing of all a sudden.

It looks for `origin/main` even though our main branch is `origin/master`

**Comment by LayZeeDK** [comment]
@ShayDavidson try passing the `main-branch-name` parameter:
```yaml
- name: Derive appropriate SHAs for base and head for `nx affected` commands
  uses: nrwl/nx-set-shas@v2.2.3
  with:
    main-branch-name: master
```

**Comment by LayZeeDK** [comment]
@charsleysa you also mention *master branches*. Is your default branch also called `master`, not `main`?

**Comment by LayZeeDK** [comment]
@meeroslav
Seems like #52 should have first of all been versioned but also force a major version bump due to breaking changes as the default branch name might not be `main` for everyone, forcing them to add a parameter (breaking change).

**Comment by JamesHenry** [comment]
Hi Folks, @meeroslav is unavailable right now so I have reverted #52 and cut a new patch release. He will get back to you soon regarding reimplementing the change

**Comment by meeroslav** [comment]
@charsleysa can you please post the snippet from your CI yaml where you call Nx-set-shas? It looks like main branch name was empty string so bash took the next non-empty value which was "false". It should have been "main" by default

**Comment by charsleysa** [comment]
@meeroslav here's the snippet
```
- name: Derive appropriate SHAs for base and head for `nx affected` commands
              uses: nrwl/nx-set-shas@v2
              with:
                  main-branch-name: ${{ github.base_ref }}
```

I've double checked and have determined that there is a bug in our CI yaml where we are using `github.base_ref` for all CI runs when it's only available for pull requests and not pushes (which is what gets triggered when you merge a pull request. 

Before #52 was merged my bug was kind of hidden by `nx-set-shas` since it didn't use the branch name specified so it continued to work.

In light of this I would not necessarily consider #52 a breaking change as it wasn't an intentionally supported use case.

**Comment by LayZeeDK** [comment]
> @charsleysa can you please post the snippet from your CI yaml where you call `nx-set-shas`? It looks like `main-branch-name` was empty so bash took the next non-empty value which was "false". It should have been "main" by default.

More likely it was the Node.js script because it isn't using named parameters. This should be fixed by #56.

**Comment by meeroslav** [comment]
Thank you. Unfortunately, unless something like `${{ github.base_ref || "main" }}` works for your scenario, you would have to split workflows per base branch to ensure main branch name is correctly set.

Despite this not being breaking change by design, as Lars pointed out, adding this change would apparently break a lot of CI setups, so it's easier for us to bump the major instead.

**Comment by LayZeeDK** [comment]
```yaml
- name: Derive appropriate SHAs for base and head for `nx affected` commands
  uses: nrwl/nx-set-shas@v2
  with:
    # Target branch name for `pull_request` events. Branch name the commit is pushed to for `push` events.
    # No other events supported for now.
    main-branch-name: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
```
