### ISSUE TITLE
Issue with affected + caching

### ISSUE THREAD

**Issue by dstoyanoff** [nrwl/nx-set-shas#68]
Hey guys,
We are using this action to trigger only the appropriate deploys when merging and it's been working great. However, I have an issue with the caching of NX in combination with this action.

(it happens in some other cases that I cannot really catch, but this one should be the cleanest example)
Imagine I've pushed a commit, where App1 has been changed, but its build failed for some reason. I didn't see that and pushed another commit in App2. 

At that point, the affected command will correctly see that both apps had been changed, because there was no successful build in between. However, one of the steps of App1 is to push a docker image with tag equal to the github build number. This step had succeeded in the previous build, so now nx would cache it, instead of execute it again, which in fact results in trying to deploy App1 (because it was affected), but that image does not really exist.

Perhaps the workflow isn't the best, but I didn't find a way to get the list of affected projects (so the deployment knows the list of projects to deploy), so I've defined a "mark" command for each deployable project that pretty much writes a file in a directory, which I later use to determine if the project needs to be deployed.

Thanks in advance

**Comment by meeroslav** [comment]
Hm, yes, it's definitely the issue of your workflow.

Usually steps like generating docker images, deployments etc. should go at the end once you pass "the usual suspects" - lint, build, test, e2e. That way you would not end up having a cached docker image for a failed run.

I didn't quite understand how that step "pushes the docker image, but it doesn't exist at the end", so I might have misunderstood your scenario.

For the list of affected projects you can use `nx print-affected --select=projects` and add target if needed e.g.
```
nx print-affected --select=projects --target=docker
```

**Comment by dstoyanoff** [comment]
Hey,
thanks for your reply. I don't need to print the affected projects, I need to pass them to the deployment phase. We use an infrastructure as code tool called Pulumi. I need to somehow pass the affected projects to Pulumi, so currently I've defined a "mark" step on each deployable project, which basically writes a file to the file system, helping me understand which projects changed.

The docker push step is the last step before the deployment. If the deployment fails for some reason, that would leave me with pushed docker images, but failed deployment (thus failed run in general). On the next run, NX sees that there is no change and doesn't execute the docker push, which would again fail the deployment due to missing docker tags (docker tags use the current GH build number, so the deployment would expect version X, while the previous run produced version X - 1.

I am happy to change my workflow if there is a better option. This is what I've managed to implement given what I could find in the NX docs.

**Comment by meeroslav** [comment]
The print-affected is more than a simple console.log. You can use the shell command to save all the affected projects.

```yaml
      # this step returns projects as a list: "project-a, project-b, other-project"
      - name: Check affected projects
        id: affected-projects
        run: |
          projects="$(yarn -s nx print-affected --target=deploy --select=projects)"
          echo ::set-output name=projects::$projects
      
      # use the exported list from the step above    
      - name: Deployment
         run: |
          echo "Affected projects: ${{ steps.affected-projects.outputs.projects }}"
```

There are two potential solutions to your problem:
- Have an integrated deploy target that pushes the docker image & deploys the project. If the deployment fails, your entire target is marked as failed and the docker image is not cached
- Do not cache the docker push target; instead, push it every time
