### ISSUE TITLE
Ability to use the override configuration on PRs

### ISSUE THREAD

**Issue by cody2094** [nrwl/nx-set-shas#70]
Currently, we can't use any of the configuration options when running on a PR based action. In my particular case, I'd love to :

1. Be able to run a workflow test that uses nx-set-shas configuration options safely on a PR using a label based event
2. Be able to have a PR label event compare the current PR against the latest release as opposed to whats on main.

I _think_ I can achieve this by doing some work to grab the latest release and then pumping that in as a branch, but I haven't tested it yet. In general though, why can't we use the configuration in a PR based event?

EDIT:

It does not appear that you can throw the release tag in as the `main-branch-name` in order to pull that particular tag

**Comment by meeroslav** [comment]
Hi @cody2094,

1. What would a PR label compare to? What would be the base? This command should work, if it doesn't please create a separate issue:
```yaml
on:
  label:
    types: [created]

jobs:
  myjob:
     # ... more configuration
     steps:
        # ... more steps     
        - name: Derive appropriate SHAs for base and head for `nx affected` commands
          uses: nrwl/nx-set-shas@v3
          with:
            last-successful-event: 'label'
        # ... more steps               
```

2. This is a very specific requirement that does not require `nx-set-shas`. The purpose of this Action is to solve the problem listed on the readme where failed runs get swallowed. You can use git commands to retrieve the top SHA of your release branch.

If you already have a release tag then you can simply use that as a base:
```yaml
- name: Get release SHA
  id: release-sha
  run: |
    # this gets the top commit with "myreleasetag"
    SHA="$(git rev-list -n 1 tags/myreleasetag)"
    echo ::set-output name=sha::$SHA
    
- name: Build
  run: npx nx affected --target=build --base=${{ steps.release-sha.outputs.sha }}
```
