### ISSUE TITLE
Wrong SHAs being set (apparently)

### ISSUE THREAD

**Issue by gaspardip** [nrwl/nx-set-shas#75]
I currently have a `turborepo` setup where I try to detect affected packages between 2 commits using `turbo run build --filter=[<sha1>...<sha2>] --dry-run` ([docs on filtering](https://turborepo.org/docs/core-concepts/monorepos/filtering)), which is very similar to `nx affected`. As per [this comment](https://github.com/vercel/turbo/discussions/800#discussioncomment-3341416)'s suggestion, I tried this action out but for some reason I think it's setting the wrong SHA as the `head`.

The action goes like this:

```yml
name: Deploy to Preview Channel

on:
  pull_request:
    branches: [master, develop]
    types: [opened, synchronize, reopened]

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Derive appropriate SHAs for base and head
        id: setSHAs
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ env.BRANCH }}
          error-on-no-successful-workflow: true
      - name: Get changes
        id: get-changes
        run: |
          echo "changes=$(npm run build --silent -- --filter=./apps/*[${{ steps.setSHAs.outputs.head }}...${{ steps.setSHAs.outputs.base }}] --dry-run=json | jq --compact-output --raw-output '.packages')" >> $GITHUB_OUTPUT
      - name: Set matrix
        id: set-matrix
        env:
          CHANGES: ${{ steps.get-changes.outputs.changes }}
        run: |
          echo "matrix={\"app\":${{ toJSON(env.CHANGES) }}}" >> $GITHUB_OUTPUT
```

From the last workflow run I see the SHAs are correctly set and expanded

```
2022-10-25T11:36:06.9772701Z ##[group]Run echo "changes=$(npm run build --silent -- --filter=./apps/*[d5d165997149a71e9d015beb2ec9a3503dda8c46...9ae8553e2890ea6c628b738d01ead3b013d24f38] --dry-run=json | jq --compact-output --raw-output '.packages')" >> $GITHUB_OUTPUT
2022-10-25T11:36:06.9773594Z [36;1mecho "changes=$(npm run build --silent -- --filter=./apps/*[d5d165997149a71e9d015beb2ec9a3503dda8c46...9ae8553e2890ea6c628b738d01ead3b013d24f38] --dry-run=json | jq --compact-output --raw-output '.packages')" >> $GITHUB_OUTPUT[0m
2022-10-25T11:36:06.9825524Z shell: /usr/bin/bash -e {0}
2022-10-25T11:36:06.9825771Z env:
2022-10-25T11:36:06.9825986Z   BRANCH: feature/wf
2022-10-25T11:36:06.9826255Z   NX_BASE: 9ae8553e2890ea6c628b738d01ead3b013d24f38
2022-10-25T11:36:06.9826543Z   NX_HEAD: d5d165997149a71e9d015beb2ec9a3503dda8c46
2022-10-25T11:36:06.9826793Z ##[endgroup]
```

but one of those doesn't exist

```
git show 9ae8553e2890ea6c628b738d01ead3b013d24f38
commit 9ae8553e2890ea6c628b738d01ead3b013d24f38 (HEAD -> feature/wf, origin/feature/wf) 
```

```
git show d5d165997149a71e9d015beb2ec9a3503dda8c46
fatal: bad object d5d165997149a71e9d015beb2ec9a3503dda8c46
```

so `turbo` yields an empty diff between those 2 commits. I previously tried to use the source branch and target branches (`github.head_ref` and `github.base_ref`) as `--filter`s and it seemed to work, so not sure what's going on.

**Comment by meeroslav** [comment]
Hey @gaspardip, thank you for reaching out.

If you use `nx-set-shas` for PRs only you don't benefit too much from its logic. The only thing it does for PRs is call:
```
git merge-base origin/${mainBranchName} HEAD
```

Which in this case would be `develop` or `master` and this results in `9ae8553e2890ea6c628b738d01ead3b013d24f38` in your case. The other parameter (head) is calculated with a simple:
```
git rev-parse HEAD
```

This should result in your head SHA. If that's missing, the only thing that comes to mind is that there was a force push that had overridden that commit.

Try running the above command in terminal on the branch and see what you get.

**Comment by TonyWhiteSMS** [comment]
I am suspecting a similar issue
```
      - name: 'Get last successful commit'
        uses: nrwl/nx-set-shas@v3
        id: setSHAs
        with:
          main-branch-name: ${{env.BRANCH_NAME}}
          last-successful-event: 'workflow_dispatch'
          workflow-id: ${{env.WORKFLOW_ID}}
```

Where BRANCH_NAME is the current branch, as we do a BRANCH deploys to an env of that same name

I noticed without committing on my branch the NX_BASE value changed without a successful build on my branch.

```
Found the last successful workflow run on 'origin/HSRDEV'
Commit: 7c1cd7634f0ad2f1ef79e90fe655cd4248034f5d
Run echo "Base SHA"
Base SHA
7c1cd7634f0ad2f1ef79e90fe655cd4248034f5d

Head SHA
db8637acd7345ec6a42c298d8935a78033d1abf5
```

And when I go to
https://github.com/..../..../commit/7c1cd7634f0ad2f1ef79e90fe655cd4248034f5d in the browser, that is the latest merge on a different branch, and the same workflow was run on that branch.

**Comment by TonyWhiteSMS** [comment]
Ahh I see, it only uses the branch for events of pull_request

**Comment by TonyWhiteSMS** [comment]
FYI - As an experiment, I have have taken a fork and found that removing the check for event being push, and including the branch in the request, returns only the workflow runs for the branch.

```
// fetch all workflow runs on a given repo/branch/workflow with push and success
  const shas = await octokit.request(`GET /repos/${owner}/${repo}/actions/workflows/${workflow_id}/runs`, {
    owner,
    repo,
    branch: branch,
    workflow_id,
    event: lastSuccessfulEvent,
    status: 'success'
    }).then(({ data: { workflow_runs } }) => workflow_runs.map(run => run.head_sha));
```

**Comment by SethDavenport** [comment]
I ran in to the same thing - I expected NX_BASE to be
1) the last successful run on the `main` branch
2) the common ancestor a non-main branch, even on the `push` event.

Instead, (2) appears to only be true for non-main branches on the `pull-request` event. This is unexpected, because I want my workflow to run on any push to a PR, not just when I open it.

Is there a chance this behaviour be made configurable?

**Comment by SethDavenport** [comment]
I ended up hacking it like this:

```
name: Checks
on: [push]
jobs:
  preflight_check:
    # ...
    steps:
      - name: Set NX_BASE for main branch
        uses: nrwl/nx-set-shas@v3
        if:
          ${{ github.ref == 'refs/heads/main' ||
          contains(github.ref,'gh-readonly-queue') || contains(github.ref,
          'release') }}

      - name: Set NX_BASE for PR branch
        if:
          ${{ github.ref != 'refs/heads/main' && !contains(github.ref,
          'gh-readonly-queue') && !contains(github.ref, 'hotfix') &&
          !contains(github.ref, 'release/') }}
        run: |
          echo "NX_BASE=$(git merge-base origin/main HEAD)" >> $GITHUB_ENV
          echo "NX_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "NX_BASE and NX_HEAD environment variables have been set for the current PR"
          echo "  NX_BASE: $NX_BASE"
          echo "  NX_HEAD: $NX_HEAD"
```

Obviously this relies on some assumptions around how our team names branches, but it does the trick.

**Comment by meeroslav** [comment]
I just reviewed the config in the original issue. The main branch setting is incorrect:
```yaml

on:
  pull_request:
    branches: [master, develop] # this yields your main branches will be master or develop
    types: [opened, synchronize, reopened] # you can drop this as it's default value

env:
  BRANCH: ${{ github.head_ref || github.ref_name }} # BRANCH gets the name of the PR branch - e.g. `feature-1`
  
jobs:
  setup:
    ...
    steps:
      - name: Derive appropriate SHAs for base and head
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ env.BRANCH }} # here you set the incorrect branch
          error-on-no-successful-workflow: true
```

The `main-branch-name` should have the value of `github.base_ref`.

You can modify it to this:
```yaml
env:
  BRANCH: ${{ github.base_ref }}
```
