### ISSUE TITLE
Not working on master with pull requests "No projects with ... were run - Successfully ran target ... for 0 projects"

### ISSUE THREAD

**Issue by mklueh** [nrwl/nx-set-shas#83]
Hello,

I'm facing a second issue with this plugin and I'm not able to get it working on master (on develop and feature branches it works except for the other issue I've created https://github.com/nrwl/nx-set-shas/issues/82)

Currently, when create a pull request to merge develop into master including squashing, it will always result in 

```
Run nx affected 

 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 7e78f982b[23](https://github.com/.../actions/runs/.../jobs/...#step:10:24)1ed3b5ceee2f465df873[24](https://github.com/.../actions/runs/.../jobs/...#step:10:25)7cdb643

 >  NX   No projects with "build-and-deploy" were run

 >  NX   Successfully ran target build-and-deploy for 0 projects
```

this is my configuration

```
on:
  pull_request:
    branches:
      - "master"
      - "main"
    types: [ closed ]

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 15
    permissions:
      contents: 'read'
      actions: 'read'

    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - run: npm install -g yarn

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        id: setSHAs
        with:
          main-branch-name: 'master'

      - name: Show head and base
        run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Deploying changed apps
        run: |
            nx affected \
            --nx-bail \
            --parallel=3 \
            --base=${{ env.NX_BASE }} \
            --target=build-and-deploy \
            --verbose
```

Head and base SHA's are always equal on master and point to the current pull request commit

This is also the same configuration like in the official Nx demo project https://github.com/nrwl/board-game-hoard/blob/master/.github/workflows/release.yml

However, this is using push events and not pull_request events

```
on:
  push:
    branches:
      - 'main'
```

What am I doing wrong?
