### ISSUE TITLE
Not valid object name origin/main

### ISSUE THREAD

**Issue by emouragym** [nrwl/nx-set-shas#88]
Hello I am having trouble running nx affected command in a github action (works perfectly localy).

### This is my action :
```yaml
name: CI
on:
  pull_request:
    paths-ignore: # <-- Exclude readmes here.
      - 'docs/**'
      - 'example/**'
    branches: [main]
jobs:
  ci:
    name: Build, lint, and test and publish preview
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@org'
          always-auth: true 
          token : ${{ secrets.GITHUB_TOKEN }}
          cache : "npm" 
      - name: Authenticate with GitHub package registry
        run:
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
          ~/.npmrc

      - name: Install global nx
        run: npm install -g nx

      - name: Setup NX 
        uses: nrwl/nx-set-shas@v3
        with: 
          main-branch-name : "main"
         
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: nx affected --target=lint  --parallel=3
```
        
### Things I have tried

-  Passing --base=main as argument to affect
-  Not using SHA action (it fails says fatal: ambiguous argument 'main': unknown revision or path not in the working tree.)

Am I missing some configuration?

**Comment by clarkenciel** [comment]
I ran into this issue as well and found that I needed the following in the "Checkout repo" step:

```yaml
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
```

Without that line `nx-set-shas` won't have access to remote branches and commits. The snippet in the README has this configuration, but if you're reading quickly (as I was 😅 ) it's easy to miss.
