### ISSUE TITLE
Document workarounds for Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by nponeccop** [nrwl/nx-set-shas#89]
I have the following file in a recently created private repo:

```
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: node -v
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v3
        with:
          set-environment-variables-for-job: false
```

It fails with the "Error: Resource not accessible by integration" error message:

![image](https://user-images.githubusercontent.com/528415/233839677-23eca58a-cf3c-41a6-9e95-2703ffcc81f6.png)

It can be fixed by adding write permissions to actions in the project settings. But it's not clear why they are needed or whether they are a bug.

**Comment by nponeccop** [comment]
Upd: the following is needed either at the workflow level or at the job level:

```yaml
    permissions:
      contents: read
      actions: read
```

Contents is needed for git lone, and actions for the GitHub API call `nx-set-shas` performs.
